services:
  server:
    build:
      context: apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - /home/care1aker/apps/fiona/db/fiona.db
    restart: unless-stopped

  bot:
    build:
      context: apps/bot
      dockerfile: Dockerfile  
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
