services:
  bot:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    volumes:
      - ./apps/bot:/app
    environment:
      - NODE_ENV=production
    restart: always

  server:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    volumes:
      - ./apps/server:/app
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000:3000" 

