services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./apps/bot:/app
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "5000:5000"  # Порт для бота, если нужно для API
    logs:
      driver: "json-file"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./apps/server:/app
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000:3000"  # Порт для сервера
    logs:
      driver: "json-file"
