version: '3.8'
services:
  server:
    build:
      context: ./apps/server
    ports:
      - '${PORT}:3000'
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./db:/data/db
    restart: unless-stopped

  bot:
    build:
      context: ./apps/bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
