services:
  server:
    build:
      context: apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - ./db:/app/db  # Относительный путь для лучшей переносимости
    restart: unless-stopped

  bot:
    build:
      context: apps/bot
      dockerfile: Dockerfile  
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SERVER_URL=http://server:3000  # Добавлено для связи с сервером
    restart: unless-stopped
    depends_on:
      - server  # Гарантирует, что сервер запустится первым
