version: '3.8'
services:
  server:
    build:
      context: ./apps/server
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./db:/data/db
    restart: unless-stopped

  bot:
    build:
      context: ./apps/bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped

  database:
    image: sqlite3
    volumes:
      - ./db:/data/db
    restart: unless-stopped
