name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add Raspberry Pi to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 192.168.1.120 >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Create deployment directory on Raspberry Pi
        run: ssh care1aker@192.168.1.120 "mkdir -p /home/care1aker/fiona/"

      - name: Copy files to Raspberry Pi
        run: |
          scp -r . care1aker@192.168.1.120:/home/care1aker/fiona/

      - name: Deploy on Raspberry Pi
        run: |
          ssh care1aker@192.168.1.120 << 'EOF'
          cd /home/care1aker/fiona
          docker-compose down
          docker-compose up -d --build
          EOF
